[wallet]
#文件格式，以英文#开头是注释，会直接过滤
#主地址 victor
address = [
    #主地址 victor
    "nimble1uz985xep83mgmp2a92gyqptvr06gk6k8v9n3vv",
    #子地址
    "nimble1a67mj08trt4sxd4erhzrzgqnufma0h0khtdya3",
    "nimble1mq32psph2c9yqc2j2k8lr67zg50kjkef02tcuu",
    "nimble1fg04yu5pk0yqvvm6jq8gtg8qa8we3wf24q34t8",
    "nimble1lk30akmnnr6zpfarm2vvg9l3q0rakagqyhh5ap",
    "nimble1t4na8cxqd46cqd7jdrenp2fxrynf02d6jcsnm0",

    #主地址 victor
    "nimble1ae4h5l0aryhu9jgdrr5srvw98pn5jmn2jnfndk",
    #子地址
    "nimble144zdgs6pefudmqdj7zvfel0fe8ukd30k62jy4x",
    "nimble1tnk0guqhp6m9yrptcwnk6sgn9chm53dmv3tqrv",
]

[monitor]
api_report_log="http://127.0.0.1:8888/printlnlog"


[server]
ip="127.0.0.1"
port=8888


[clore]

#web_api_host
web_api_host="https://clore.ai/"
#请求下单接口
web_token="MTcxNjY1NDA2N19XeElVS0dJR2dpMGF4cDJzbmtOeDNWOUVyczg3amQ="

#api请求地址
api_host="https://api.clore.ai/"
#api数据接口token
api_token="v76Zfp8zmmVj-KsI7mr-kv6irmS1UC8L"
#远程连接密码
ssh_passwd="MTcxNjMwNDc2N19ZempBSW"

command="""
#!/bin/bash
cd $HOME
apt update -y 
apt install git -y
echo "export SERVER_ID={server_id}" >> $HOME/.bashrc
echo "export CARD_NUMBER={card_number}" >> $HOME/.bashrc
echo "export ADDRESS={address}" >> $HOME/.bashrc
source $HOME/.bashrc
git clone  https://github.com/zlseqx/clore.git >> $HOME/server.txt 2>&1

cd $HOME/clore
chmod +x env.sh rust.sh run.sh && ./env.sh >> $HOME/server.txt 2>&1

# 防止内部被cd,需要切换到clore目录操作
cd $HOME/clore
source $HOME/.cargo/env
source $HOME/.bashrc

# 激活pm2环境,用pm2管理cargo 监控进程
conda init
conda activate nimble
pm2 start "cargo run -r --bin monitor" --name monitor --log $HOME/clore/monitor.txt
"""





