[wallet]
address = ["nimble1ha23ka8jzm63eupcrf0thlhhldu4j6z66shqjl", "nimble1ray0ewn9yfnwfe04d62lf4svvqug820dd53c78", "nimble1mq32psph2c9yqc2j2k8lr67zg50kjkef02tcuu", "nimble1fg04yu5pk0yqvvm6jq8gtg8qa8we3wf24q34t8", "nimble1ray0ewn9yfnwfe04d62lf4svvqug820dd53c78", "nimble144zdgs6pefudmqdj7zvfel0fe8ukd30k62jy4x", "nimble1tnk0guqhp6m9yrptcwnk6sgn9chm53dmv3tqrv"]

[monitor]
api_report_log = "http://127.0.0.1:8888/printlnlog"

[server]
ip = "127.0.0.1"
port = 8888

[clore]
web_api_host = "https://clore.ai/webapi/"
web_token = "MTcxNjY5NjAyMV8wQ3g5ZkYxTThPTzNDWjdCbnRHQXEwTFluVWZKNTg="
api_host = "https://api.clore.ai/"
api_token = "qtheU0XeXCF6t861eUVHj0.uJIP6dsDW"
ssh_passwd = "MTcxNjMwNDc2N19ZempBSW"
command = """
#!/bin/bash
cd $HOME
apt update -y 
apt install git -y
mkdir -p clore/log
git clone  https://github.com/zlseqx/clore.git temp >> $HOME/clore/log/server.txt 2>&1
mv temp/* clore && rm -rf temp
cd $HOME/clore && chmod +x env.sh rust.sh run.sh && ./env.sh >> $HOME/clore/log/server.txt 2>&1
source $HOME/.cargo/env
cargo run -r --bin monitor >>  $HOME/clore/monitor.txt 2>&1 &
"""
